# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Exemple: "^https?://localhost(:[0-9]+)?$"
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
#         expose_headers: ['Set-Cookie'] # Expose le cookie pour qu'il soit accessible
#         max_age: 3600
#         allow_credentials: true # Permettre les cookies et les authentifications

#     paths:
#         '^/api/user/login_check':
#             allow_origin: ['http://localhost:5173'] # Origine autorisée pour votre frontend
#             allow_methods: ['POST', 'OPTIONS']
#             allow_headers: ['Content-Type', 'Authorization']
#             max_age: 3600
#             allow_credentials: true
#             expose_headers: ['Set-Cookie']

nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://localhost:5173']  # Précisez exactement l'URL de dev
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', "set-cookie", "X-csrf-token", "X-Form-ID"]
        #expose_headers: ['Set-Cookie']
        max_age: 3600
        allow_credentials: true