nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+', '^https://www.nationsound2024-festival.fr']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        max_age: 3600
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+', '^https://www.nationsound2024-festival.fr']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            max_age: 3600
