/////////////////////////API//////////////////////////

///////////////Programmation///////////////

// Obtenir la liste des concerts
GET http://127.0.0.1:8000/api/public/concert HTTP/1.1 

// Obtenir la liste des concerts avec des filtres
GET http://127.0.0.1:8000/api/public/concert?scene=2 HTTP/1.1

// Obtenir tous les filtres possibles pour la programmation
GET http://127.0.0.1:8000/api/public/concert/filters HTTP/1.1

///////////////Partenaires///////////////

// Obtenir la liste des partenaires
GET http://127.0.0.1:8000/api/public/partner HTTP/1.1

// Filtrer les partenaires par catégorie
GET http://127.0.0.1:8000/api/public/partner/category/4 HTTP/1.1

// Obtenir tous les filtres possibles pour les partenaires
GET http://127.0.0.1:8000/api/public/partner/category HTTP/1.1

////////////////Actualités////////////////

// Obtenir la liste des actualités sauf événements de sécurité et météo
GET http://127.0.0.1:8000/api/public/news HTTP/1.1

// Obtenir les événements de sécurité et météo
GET http://127.0.0.1:8000/api/public/news/alert HTTP/1.1

///////////////////FAQ et informations générales////////////////////

// Obtenir la FAQ et les informations générales
GET http://127.0.0.1:8000/api/public/faq HTTP/1.1

///////////////////Carte interactive////////////////////

// Obtenir les catégories de points de la carte
GET http://127.0.0.1:8000/api/public/map/points/category HTTP/1.1

// Obtenir les points de la carte
GET http://127.0.0.1:8000/api/public/map/marker/ HTTP/1.1

// Obtenir les points de la carte pour une catégorie donnée
GET http://127.0.0.1:8000/api/public/map/marker/1 HTTP/1.1
