// Route d'inscription
POST http://127.0.0.1:8000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "email": "test6@test.com",
    "password": "kljlqkjkljkljkljj!1T",
    "firstName": "Emmanuel",
    "lastName": "LASTRA"
}

// Route de connexion
POST http://127.0.0.1:8000/api/user/login_check HTTP/1.1
Content-Type: application/json

{
    "email": "test6@test.com",
    "password": "kljlqkjkljkljkljj!1T"
}

// Profil utilisateur (token sans guillemets)
// Profil utilisateur
GET http://127.0.0.1:8000/api/user/profil HTTP/1.1


// Modifier le profil utilisateur
PUT http://127.0.0.1:8000/api/user/profil/edit HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjY4Mjc3NzgsImV4cCI6MTcyNjgzMTM3OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdDZAdGVzdC5jb20ifQ.Pj58r4HrSM0RgzQTVKYC9yTjNipjQPAbZNPjLL5c6jp0zYPYfteb48hO7KjLSw5VIdaPMc33OUBr-VzsZqlxmsA32KBmuqFKfCpmz-9n5CFPypKXHboTmB7Aq0gkcobxuz3hT1hpeGDSTpH2t-UDBGv2rL-pKZUbHgLDWbIooXhFgVQn0UIxjY6wAWxamntF95ZCxxb9xZR45Ppp8vxi4WurEdJqP7vntPNrwAX7J330CK8dHHrI7PPxBXrnK-4M5p7WIjH6s496DWPqcfDiOuIMLlH77MIFatHmKaqm-WZMj0YeuVXWbQZBooKu_9pP2zs6y0v3Dmj9c29b399uFQ
Content-Type: application/json

{
    "firstName": "Jules",
    "lastName": "Cesars",
    "newsletter": true
}

// Supprimer le profil utilisateur
DELETE http://127.0.0.1:8000/api/user/profil/delete HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjY4Mjc3NzgsImV4cCI6MTcyNjgzMTM3OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdDZAdGVzdC5jb20ifQ.Pj58r4HrSM0RgzQTVKYC9yTjNipjQPAbZNPjLL5c6jp0zYPYfteb48hO7KjLSw5VIdaPMc33OUBr-VzsZqlxmsA32KBmuqFKfCpmz-9n5CFPypKXHboTmB7Aq0gkcobxuz3hT1hpeGDSTpH2t-UDBGv2rL-pKZUbHgLDWbIooXhFgVQn0UIxjY6wAWxamntF95ZCxxb9xZR45Ppp8vxi4WurEdJqP7vntPNrwAX7J330CK8dHHrI7PPxBXrnK-4M5p7WIjH6s496DWPqcfDiOuIMLlH77MIFatHmKaqm-WZMj0YeuVXWbQZBooKu_9pP2zs6y0v3Dmj9c29b399uFQ
