controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_admin_login:
    path: /admin/login
    controller: App\Controller\AdminSecurityController::login

app_admin_logout:
    path: /admin/logout
    controller: App\Controller\AdminSecurityController::logout

api_user_login:
    path: /api/user/login_check
    methods: POST
    
   
    

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin/login
        permanent: true